#!/usr/bin/env python

# A small script to invoke cfx from the jetpack platform with proper arguments.
# accepts a single argument on the command line which is the path to the
# "entry point HTML" - that which should be used as the browser's UI.

import os,sys

# given a filename argument, return an absolute path
def findBrowserHTML(path):
    # "ui" directory can be omitted, but we'll automatically append it to
    # verify that file exists.
    if not os.path.exists(path):
        path = os.path.join("ui", path)
    if os.path.isdir(path):
        path = os.path.join(path, "index.html")
    # the path we return must have ui omitted
    return os.path.abspath(path)

# be flexible in handling the first argument
browserToLaunch = "first_browser/index.html"
try:
    browserToLaunch = sys.argv[1]
except:
    pass
browserToLaunch = findBrowserHTML(browserToLaunch)

# throw an error message if we can't figure out what html file
# is the browser's HTML entry point
if not os.path.exists(browserToLaunch):
    print >>sys.stderr, "can't find browser HTML (tried '"+browserToLaunch+"')"
    raise SystemExit(1)

print "Will open the browser HTML = "+ browserToLaunch
print "You can also try other scripts such as ./run ui/thumbnails/index.html"

# now let's run the cfx thingy and specify the app-kit main module
# as our starting point
os.system("impl/bin/cfx -a xulrunner -t ./template/app-extension " + \
          "--static-args {\\\"browser\\\":\\\""+ browserToLaunch+"\\\"} " + \
          "-p \"impl/packages/chromeless\" run")
